name: bus_client
description: Bus information CLI client
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.4.0
  envied: ^0.5.3
  url_launcher: ^6.2.5

assets:
  - assets/data/
  - assets/images/