name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - name: Checkout Flutter 3.24.1
        shell: bash
        run: |
            cd $FLUTTER_ROOT;
            git fetch --tags;
            git checkout 3.24.1;
            flutter --version;

      - name: Install dependencies
        run: flutter pub get
        working-directory: front

      - name: Run tests
        run: flutter test
        working-directory: front